### ISSUE TITLE
Тесты форматирования имен

### ISSUE THREAD

**Issue by dimakarov** [HyperLEDA/db-app#64]
And XXVIII, Andromeda XXVIII, And28, ANDXXVIII,  andxxviii, andromeda28 => Andromeda 28
Holmberg II, Holm II, HoII, Ho2, Holmberg 2, Holm2 => Holmberg 2
7ZW223, VII Zw 223, ZW VII 223 => 7ZW 223
NGC0017, N17, ngc17, n017 => NGC 17
UGC 1493 A, u1493a, ugc1439a, u1493A => UGC 1493A
UGCA 035, ua35, UA035 UGCA35 => UGCA 35
LEDA9843, PGC 9843, p009843, leda 009843, PGC009843 => PGC 9843
ESO413-003, eso 413-3, ESO 413-03, ESO 413- G 003 => ESO 413-3
ESO-LV 2530200, ESO-LV 2530200, ESO-LV 253-0200 => ESO-LV 2530200
6dF J0544383-434609, 6dFJ0544383-434609 => 6dF J0544383-434609
Virgo A, Vir A => Virgo A
SDSS J123049.41+122328.1, sdssJ123049.41+122328.1 => SDSS J123049.41+122328.1

**Comment by d-makarov-d** [comment]
Ветка задачи `name-standard`
Требуется реализовать `GeneralizeNameUseCase` (https://github.com/HyperLEDA/db-app/blob/name-standard/app/domain/usecases/generalize_name_use_case.py) так, чтобы прошли тесты в `GeneralizeNameTest` (https://github.com/HyperLEDA/db-app/blob/name-standard/tests/domain/generalize_name_test.py)
